TypeScript declarations, RemoveEmptyLines, TrimLines, InsertFinalNewLine
AdguardTeam/HostlistCompiler pull request #33
Opened 2022-06-02 22:11 UTC by scripthunter7

- TypeScript declarations + JSoc
  - Suggestions in VSCode: 
   ![image](https://user-images.githubusercontent.com/57285466/171745804-7ba0449d-6542-40e1-a2e2-987216398f8b.png)
- `RemoveEmptyLines`
  - Input:
    ```
    rule1

    rule2

    rule3
    ```
  - Output:
    ```
    rule1
    rule2
    rule3
    ```
- `TrimLines`
  - Input:
    ```
    rule1
      rule2
            rule3
        rule4
    ```
  - Output:
    ```
    rule1
    rule2
    rule3
    rule4
    ```
- `InsertFinalNewLine`
  - Input:
    ```
    rule1
    rule2
    ```
  - Output:
    ```
    rule1
    rule2

    ```

## Test example

Input file `test.txt`:
```

        ||ads.geeks.hu^     
||adv.forpsi.hu^
||adv.hu^       
                ||adverbs.napilapcsoport.hu^
||advert*.ultraweb.hu^

! random comment

            ||adverticum.*.hu^
||app.livechatoo.com^
||as*.prog.hu^
! duplicate
||audit.median.hu^
||audit.median.hu^

||avatraffic.com^
||banner.terminal.hu^
||banner.webtar.hu^
```

Test script: `hostlist-compiler-test.ts`
```typescript
import compile from '@adguard/hostlist-compiler';
import { writeFileSync } from 'fs';

(async () => {
    // Compile filters
    const result = await compile({
        name: 'Test Output',
        sources: [
            {
                type: 'adblock',
                source: 'release/test.txt',
                transformations: ['RemoveComments', 'Validate'],
            },
        ],
        transformations: ['Deduplicate', 'RemoveEmptyLines', 'TrimLines', 'InsertFinalNewLine'],
    });

    // Write to file
    writeFileSync('test-output.txt', result.join('\n'));
})();
```

Output  file `test-output.txt`:
```
!
! Title: Test Output
! Last modified: 2022-06-02T22:08:39.598Z
!
! Compiled by @adguard/hostlist-compiler v1.0.14
!
!
! Source: release/test.txt
!
||ads.geeks.hu^
||adv.forpsi.hu^
||adv.hu^
||adverbs.napilapcsoport.hu^
||advert*.ultraweb.hu^
||adverticum.*.hu^
||app.livechatoo.com^
||as*.prog.hu^
||audit.median.hu^
||avatraffic.com^
||banner.terminal.hu^
||banner.webtar.hu^
```

## "Real life" usage

`hufilter-dns.ts`:
```typescript
import HostlistCompiler, { IConfiguration as HostlistCompilerConfiguration } from '@adguard/hostlist-compiler';
import { writeFileSync } from 'fs';

;(async () => {
    // Configuration
    const config: HostlistCompilerConfiguration = {
        name: 'hufilter DNS filter',
        description: 'Simplified hufilter version specifically to be better compatible with DNS-level ad blocking.',
        homepage: 'https://github.com/hufilter/hufilter/wiki',
        license: 'https://github.com/hufilter/hufilter/blob/master/LICENSE',
        sources: [
            {
                type: 'adblock',
                source: 'https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-adguard.txt',
                transformations: ['RemoveComments', 'Validate'],
            },
        ],
        transformations: ['Deduplicate', 'RemoveEmptyLines', 'TrimLines', 'InsertFinalNewLine'],
    };

    // Compile
    const result = await HostlistCompiler(config);

    // Write to file
    writeFileSync('hufilter-dns.txt', result.join('\n'));
})();
```

## Related issues
- https://github.com/AdguardTeam/HostlistCompiler/issues/12
- https://github.com/AdguardTeam/HostlistCompiler/issues/30

2022-06-03 15:47 UTC, ameshkov commented
@scripthunter7 thank you for the contribution! @tvinzz will take care of it.

2022-06-09 05:19 UTC, maximtop commented on src/transformations/trim-lines.js
> +    const transformed = lines.map((line) => _.trim(line, [' ', '\t']));
@scripthunter7 lodash `_.trim` function for the second argument takes string, not array
with the array, it implicitly trims commas in the lines too, though there are no such cases in the tests

2022-06-09 05:22 UTC, maximtop requested changes
please fix

2022-06-09 08:05 UTC, scripthunter7 commented
> please fix

@maximtop Thank you! Fixed, see https://github.com/AdguardTeam/HostlistCompiler/pull/33/commits/dbf44ade565dee005248b2fd16105bb92330a2d0

2022-06-14 09:12 UTC, merged